INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('7', 'Nguyễn',  'Văn An ', '0736690849', '04/05/2004',' nguyenvanan354@gmail.com', crypt('nguyenvanan',gen_salt('md5')),'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('8', 'Lê',  'Minh Quân', '0702066430', '20/02/1991',' leminhquan123@gmail.com', crypt('leminhquan',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('9', 'Trần',  'Hữu Nam', '0871561535', '08/07/1996',' tranhuunam783@gmail.com', crypt('tranhuunam',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('10', 'Phạm',  'Gia Bảo', '0406685975', '18/09/2003',' phamgiabao512@gmail.com', crypt('phamgiabao',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('11', 'Hoàng',  'Thanh Hải', '0924338810', '12/10/2001',' hoangthanhhai172@gmail.com', crypt('hoangthanhhai',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('12', 'Đặng',  'Thuận Phong', '0272797780', '21/09/1990',' dangthuanphong981@gmail.com', crypt('dangthuanphong',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('13', 'Võ',  'Đức Minh', '0277658862', '08/02/2005',' voducminh997@gmail.com', crypt('voducminh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('14', 'Bùi',  'Anh Khoa', '0191523679', '18/04/2001',' buianhkhoa655@gmail.com', crypt('buianhkhoa',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('15', 'Nguyễn',  'Đức Long', '0669828057', '27/10/1997',' nguyenduclong48@gmail.com', crypt('nguyenduclong',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('16', 'Lê',  'Mai Linh', '0453085602', '09/06/1993',' lemailinh45@gmail.com', crypt('lemailinh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('17', 'Trần',  'Hữu Nghị', '0108810541', '24/02/1997',' tranhuunghi822@gmail.com', crypt('tranhuunghi',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('18', 'Phạm ',  'Quang Huy', '0933421235', '05/11/1997',' phamquanghuy630@gmail.com', crypt('phamquanghuy',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('19', 'Hoàng',  'Tùng Lâm', '0234091519', '28/03/1998',' hoangtunglam22@gmail.com', crypt('hoangtunglam',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('20', 'Đặng',  'Văn Sơn', '0515397093', '15/05/2005',' dangvanson629@gmail.com', crypt('dangvanson',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('21', 'Võ',  'Thanh Tùng', '0582922258', '23/03/1993',' vothanhtung981@gmail.com', crypt('vothanhtung',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('22', 'Bùi',  'Thế Vinh', '0806851357', '26/11/2002',' buithevinh202@gmail.com', crypt('buithevinh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('23', 'Nguyễn',  'Hồng Nam', '0476074808', '14/05/1992',' nguyenhongnam243@gmail.com', crypt('nguyenhongnam',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('24', 'Lê',  'Khánh Duy', '0353007370', '26/09/2003',' lekhanhduy906@gmail.com', crypt('lekhanhduy',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('25', 'Trần',  'Anh Quân', '0769558596', '08/09/1996',' trananhquan491@gmail.com', crypt('trananhquan',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('26', 'Phạm',  'Tuấn Kiệt', '0864482377', '04/01/1994',' phamtuankiet397@gmail.com', crypt('phamtuankiet',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('27', 'Hoàng',  'Xuân Phúc', '0621428938', '11/10/2005',' hoangxuanphuc685@gmail.com', crypt('hoangxuanphuc',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('28', 'Đặng',  'Đức Trí', '0897250956', '25/01/2005',' dangductri935@gmail.com', crypt('dangductri',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('29', 'Võ',  'Ngọc Thịnh', '0254573750', '15/06/2000',' vongocthinh353@gmail.com', crypt('vongocthinh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('30', 'Bùi',  'Văn Hoàng', '0912263477', '31/08/1991',' buivanhoang306@gmail.com', crypt('buivanhoang',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('31', 'Nguyễn',  'Thanh Phong', '0397898756', '14/03/2004',' nguyenthanhphong269@gmail.com', crypt('nguyenthanhphong',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('32', 'Lê',  'Minh Khôi', '0467808391', '17/08/2006',' leminhkhoi176@gmail.com', crypt('leminhkhoi',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('33', 'Trần',  'Văn Thành', '0318436056', '03/10/2000',' tranvanthanh316@gmail.com', crypt('tranvanthanh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('34', 'Phạm',  'Hữu Nghĩa', '0276245144', '03/06/1998',' phamhuunghia938@gmail.com', crypt('phamhuunghia',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('35', 'Hoàng',  'Anh Tuấn', '0379585473', '10/01/2000',' hoanganhtuan822@gmail.com', crypt('hoanganhtuan',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('36', 'Đặng',  'Quốc Bảo', '0404986812', '29/05/1992',' dangquocbao584@gmail.com', crypt('dangquocbao',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('37', 'Võ',  'Minh Huy', '0512118685', '28/07/1991',' vominhhuy339@gmail.com', crypt('vominhhuy',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('38', 'Bùi',  'Nhật Minh', '0533249246', '02/10/1998',' buinhatminh134@gmail.com', crypt('buinhatminh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('39', 'Nguyễn',  'Hoàng An', '0915448520', '24/10/1997',' nguyenhoangan754@gmail.com', crypt('nguyenhoangan',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('40', 'Lê',  'Đình Quang', '0197829064', '10/07/2002',' ledinhquang499@gmail.com', crypt('ledinhquang',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('41', 'Trần',  'Hoàng Nam', '0354976468', '27/01/1993',' tranhoangnam922@gmail.com', crypt('tranhoangnam',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('42', 'Phạm',  'Thanh Long', '0414898579', '25/07/1999',' phamthanhlong439@gmail.com', crypt('phamthanhlong',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('43', 'Hoàng',  'Mạnh Hùng', '0629224827', '18/07/1998',' hoangmanhhung699@gmail.com', crypt('hoangmanhhung',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('44', 'Đặng',  'Văn Lộc', '0696698659', '02/11/1999',' dangvanloc691@gmail.com', crypt('dangvanloc',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('45', 'Võ',  'Thành Đạt', '0485796697', '16/12/1990',' vothanhdat498@gmail.com', crypt('vothanhdat',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('46', 'Bùi',  'Quốc Việt', '0651798544', '07/07/1994',' buiquocviet671@gmail.com', crypt('buiquocviet',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('47', 'Nguyễn',  'Chí Thanh', '0989947304', '31/12/1992',' nguyenchithanh898@gmail.com', crypt('nguyenchithanh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('48', 'Lê',  'Xuân Trường', '0631373543', '12/07/1993',' lexuantruong226@gmail.com', crypt('lexuantruong',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('49', 'Trần',  'Minh Tiến', '0145259751', '22/03/2000',' tranminhtien588@gmail.com', crypt('tranminhtien',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('50', 'Phạm',  'Hùng Cường', '0087880907', '08/01/2003',' phamhungcuong898@gmail.com', crypt('phamhungcuong',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('51', 'Hoàng',  'Đức Thắng', '0566800701', '02/08/2002',' hoangducthang265@gmail.com', crypt('hoangducthang',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('52', 'Đặng',  'Vũ Hải', '0629254317', '03/12/1993',' dangvuhai289@gmail.com', crypt('dangvuhai',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('53', 'Võ',  'Hữu Bình', '0472879864', '02/07/1999',' vohuubinh578@gmail.com', crypt('vohuubinh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('54', 'Bùi',  'Công Thành', '0729820594', '16/06/2004',' buicongthanh844@gmail.com', crypt('buicongthanh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('55', 'Nguyễn',  'Tấn Phát', '0139829210', '01/12/2005',' nguyentanphat111@gmail.com', crypt('nguyentanphat',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('56', 'Lê',  'Trung Kiên', '0192683657', '17/02/1998',' letrungkien956@gmail.com', crypt('letrungkien',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('57', 'Trần',  'Anh Dũng', '0231925155', '10/12/2004',' trananhdung368@gmail.com', crypt('trananhdung',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('58', 'Phạm',  'Văn Bình', '0208626626', '04/09/1994',' phamvanbinh661@gmail.com', crypt('phamvanbinh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('59', 'Hoàng',  'Ngọc Minh', '0658460943', '10/09/1990',' hoangngocminh247@gmail.com', crypt('hoangngocminh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('60', 'Đặng',  'Quang Minh', '0323131198', '03/01/2000',' dangquangminh877@gmail.com', crypt('dangquangminh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('61', 'Võ',  'Đình Tùng', '0378304158', '03/01/2004',' vodinhtung873@gmail.com', crypt('vodinhtung',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('62', 'Bùi',  'Anh Dũng', '0509551004', '28/12/1994',' buianhdung303@gmail.com', crypt('buianhdung',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('63', 'Nguyễn',  'Huy Hoàng', '0589187970', '08/03/1996',' nguyenhuyhoang425@gmail.com', crypt('nguyenhuyhoang',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('64', 'Lê',  'Quốc Thắng', '0323601827', '03/10/2005',' lequocthang360@gmail.com', crypt('lequocthang',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('65', 'Trần',  'Văn Hiếu', '0411039228', '20/11/1993',' tranvanhieu803@gmail.com', crypt('tranvanhieu',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('66', 'Phạm',  'Minh Đức', '0266172087', '03/11/1993',' phamminhduc875@gmail.com', crypt('phamminhduc',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('67', 'Hoàng',  'Trung Hiếu', '0271915346', '25/06/1999',' hoangtrunghieu780@gmail.com', crypt('hoangtrunghieu',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('68', 'Đặng',  'Thanh Sơn', '0565712100', '24/06/2000',' dangthanhson805@gmail.com', crypt('dangthanhson',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('69', 'Võ',  'Quang Huy', '0982669283', '12/02/1997',' voquanghuy125@gmail.com', crypt('voquanghuy',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('70', 'Bùi',  'Tấn Hưng', '0541428163', '08/07/1992',' buitanhung279@gmail.com', crypt('buitanhung',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('71', 'Nguyễn',  'Văn Khoa', '0366643900', '19/10/2004',' nguyenvankhoa444@gmail.com', crypt('nguyenvankhoa',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('72', 'Lê',  'Tuấn Anh', '0584960405', '05/12/1994',' letuananh513@gmail.com', crypt('letuananh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('73', 'Trần',  'Xuân Hùng', '0112246719', '02/02/1997',' tranxuanhung491@gmail.com', crypt('tranxuanhung',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('74', 'Phạm',  'Thanh Phong', '0937995916', '04/11/2003',' phamthanhphong677@gmail.com', crypt('phamthanhphong',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('75', 'Hoàng',  'Hải Nam', '0201151628', '19/12/2004',' hoanghainam122@gmail.com', crypt('hoanghainam',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('76', 'Đặng',  'Anh Khoa', '0968891752', '25/08/2002',' danganhkhoa375@gmail.com', crypt('danganhkhoa',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('77', 'Võ',  'Tấn Lộc', '0865965679', '10/06/2002',' votanloc797@gmail.com', crypt('votanloc',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('78', 'Bùi',  'Quang Vinh', '0224128307', '05/03/1991',' buiquangvinh568@gmail.com', crypt('buiquangvinh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('79', 'Nguyễn',  'Thế An', '0903202621', '12/06/2000',' nguyenthean756@gmail.com', crypt('nguyenthean',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('80', 'Lê',  'Vũ Hùng', '0368379474', '29/05/2006',' levuhung384@gmail.com', crypt('levuhung',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('81', 'Trần',  'Văn Nghĩa', '0275788052', '23/02/2006',' tranvannghia721@gmail.com', crypt('tranvannghia',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('82', 'Phạm',  'Ngọc Sơn', '0904604254', '16/06/1997',' phamngocson591@gmail.com', crypt('phamngocson',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('83', 'Hoàng',  'Minh Huy', '0629061721', '10/12/2003',' hoangminhhuy913@gmail.com', crypt('hoangminhhuy',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('84', 'Đặng',  'Hữu Tài', '0508181200', '23/01/1999',' danghuutai773@gmail.com', crypt('danghuutai',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('85', 'Võ',  'Chí Dũng', '0965390731', '08/11/2005',' vochidung732@gmail.com', crypt('vochidung',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('86', 'Bùi',  'Hữu Long', '0372884338', '02/11/2005',' buihuulong68@gmail.com', crypt('buihuulong',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('87', 'Nguyễn',  'Quốc Khánh', '0971783024', '06/10/1997',' nguyenquockhanh444@gmail.com', crypt('nguyenquockhanh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('88', 'Lê',  'Văn Lâm', '0573130212', '17/02/1992',' levanlam105@gmail.com', crypt('levanlam',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('89', 'Trần',  'Huy Vũ', '0781161470', '01/12/1995',' tranhuyvu435@gmail.com', crypt('tranhuyvu',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('90', 'Phạm',  'Đình Thành', '0411550079', '22/10/2000',' phamdinhthanh654@gmail.com', crypt('phamdinhthanh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('91', 'Hoàng',  'Văn Trung', '0176704862', '21/01/1998',' hoangvantrung740@gmail.com', crypt('hoangvantrung',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('92', 'Đặng',  'Thế Vũ', '0355063902', '10/04/1990',' dangthevu256@gmail.com', crypt('dangthevu',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('93', 'Võ',  'Huy Hoàng', '0655861505', '19/01/1996',' vohuyhoang750@gmail.com', crypt('vohuyhoang',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('94', 'Bùi',  'Khắc Hoàng', '0901881407', '01/01/1992',' buikhachoang463@gmail.com', crypt('buikhachoang',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('95', 'Nguyễn',  'Nhật Nam', '0977464860', '04/03/1990',' nguyennhatnam590@gmail.com', crypt('nguyennhatnam',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('96', 'Lê',  'Văn Thịnh', '0766331966', '18/01/1995',' levanthinh813@gmail.com', crypt('levanthinh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('97', 'Trần',  'Đức Anh', '0017661388', '05/12/1998',' tranducanh284@gmail.com', crypt('tranducanh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('98', 'Phạm',  'Quốc Đạt', '0615733014', '15/06/1996',' phamquocdat239@gmail.com', crypt('phamquocdat',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('99', 'Hoàng',  'Hải Đăng', '0267434128', '02/03/1996',' hoanghaidang255@gmail.com', crypt('hoanghaidang',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('100', 'Đặng',  'Công Bình', '0631476676', '25/09/2004',' dangcongbinh683@gmail.com', crypt('dangcongbinh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('101', 'Võ',  'Hữu Đức', '0332815326', '05/12/1993',' vohuuduc228@gmail.com', crypt('vohuuduc',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('102', 'Bùi',  'Quang Huy', '0245383769', '02/04/2002',' buiquanghuy206@gmail.com', crypt('buiquanghuy',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('103', 'Nguyễn',  'Đăng Khoa', '0191217910', '24/10/1995',' nguyendangkhoa961@gmail.com', crypt('nguyendangkhoa',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('104', 'Lê',  'Minh Tú', '0224427625', '03/05/2000',' leminhtu661@gmail.com', crypt('leminhtu',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('105', 'Trần',  'Phúc Anh', '0226089071', '19/11/1997',' tranphucanh547@gmail.com', crypt('tranphucanh',gen_salt('md5')), 'customer');
INSERT INTO USERS(user_id, last_name, first_name, phone_number,date_of_birth, email, pass_word, user_type) values('106', 'Phạm',  'Chí Tài', '0614987082', '07/11/2005',' phamchitai820@gmail.com', crypt('phamchitai',gen_salt('md5')), 'customer');
INSERT INTO CUSTOMERS(user_id, customer_type) values('7', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('8', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('9', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('10', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('11', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('12', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('13', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('14', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('15', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('16', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('17', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('18', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('19', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('20', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('21', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('22', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('23', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('24', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('25', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('26', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('27', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('28', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('29', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('30', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('31', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('32', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('33', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('34', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('35', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('36', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('37', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('38', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('39', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('40', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('41', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('42', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('43', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('44', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('45', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('46', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('47', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('48', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('49', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('50', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('51', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('52', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('53', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('54', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('55', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('56', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('57', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('58', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('59', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('60', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('61', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('62', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('63', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('64', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('65', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('66', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('67', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('68', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('69', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('70', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('71', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('72', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('73', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('74', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('75', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('76', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('77', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('78', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('79', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('80', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('81', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('82', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('83', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('84', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('85', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('86', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('87', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('88', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('89', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('90', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('91', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('92', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('93', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('94', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('95', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('96', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('97', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('98', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('99', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('100', 'medium');
INSERT INTO CUSTOMERS(user_id, customer_type) values('101', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('102', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('103', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('104', 'normal');
INSERT INTO CUSTOMERS(user_id, customer_type) values('105', 'vip');
INSERT INTO CUSTOMERS(user_id, customer_type) values('106', 'normal');